language: python

services:
  - docker

python:
  - "3.7"

install:
  - pip install pipenv pytest
  - pipenv install
  - pytest              # <== This runs in Pipenv (a/k/a virtualenv)

# command to run tests
script:
  - pytest

before_deploy:
  - docker build -t sartography/protocol-builder-mock .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master