language: python

services:
  - postgresql
  - docker

python:
  - "3.7"

before_install:
  - cp config/travis-testing.py config/testing.py
  - psql -c 'create database pb_test;' -U postgres

install:
  - pip install pipenv pytest
  - pipenv install
  - pytest              # <== This runs in Pipenv (a/k/a virtualenv)

# command to run tests
script:
  - pytest

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com
