"""empty message

Revision ID: 6aff144771d1
Revises: 30204a978f3f
Create Date: 2020-02-17 15:03:46.017009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aff144771d1'
down_revision = '30204a978f3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_details',
    sa.Column('STUDYID', sa.Integer(), nullable=False),
    sa.Column('IS_IND', sa.Integer(), nullable=True),
    sa.Column('IND_1', sa.String(), nullable=True),
    sa.Column('IND_2', sa.String(), nullable=True),
    sa.Column('IND_3', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['STUDYID'], ['study.STUDYID'], ),
    sa.PrimaryKeyConstraint('STUDYID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_details')
    # ### end Alembic commands ###
