openapi: "3.0.2"
info:
  description: Provides access to detailed information about a protocol under definition within the IRB's Protocol Builder Application at the University of Virginia.
  version: 2.0.0
  title: Protocol Builder API
  # put the contact info for your development or API team
  contact:
    email: dan@sartography.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  # Added by API Auto Mocking Plugin
# tags are used for organizing operations
tags:
- name: CR-Connect
  description: Operations that will be available to CR Connect
paths:
  /user_studies:
    get:
      tags:
      - CR-Connect
      summary: A list of all studies related to a given UVA ID
      operationId: pb.get_user_studies
      description: "By passing in a valid UVA Id (ex: dhf8r) it will return a list of all studies that exist for that user in Protocol Builder"
      parameters:
      - in: query
        name: uva_id
        description: A valid user id for the University of Virginia.
        required: true
        schema:
          type: string
      - in: query
        name: after_date
        description: Restrict the studies to only those that were modified after the given date. Date format is yyyy-mm-dd (2019-12-25)
        schema:
          type: string
          format: date
      responses:
        '200':
          description: A list of study details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Study"
  /required_docs:
    get:
      tags:
        - CR-Connect
      summary: Required documents
      operationId: pb.required_docs
      description: A list of all documents Protocol Builder considers required, given input from the PI
      parameters:
      - in: query
        name: studyid
        description: A valid studyid, as provided in the call to list all studies.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: A list of required documents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RequiredDocument"
  /investigators:
    get:
      tags:
        - CR-Connect
      summary: Personnel associated with this study.
      operationId: pb.investigators
      description: A list of everyone that is associated with the study, including the PI, Study Coordinator, etc... This is currently returned on the "study" endpoint with other information.
      parameters:
      - in: query
        name: studyid
        description: A valid studyid, as provided in the call to list all studies.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: A list of personnel
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Investigator"
  /sponsors:
    get:
      tags:
        - CR-Connect
      summary: Sponsors associated with a study.
      operationId: pb.sponsors
      description: A list of all the sponsors related to a study
      parameters:
        - in: query
          name: studyid
          description: A valid studyid, as provided in the call to list all studies.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of sponsors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Sponsor"
  /study:
    parameters:
      - in: query
        name: studyid
        description: A valid studyid, as provided in the call to list all studies.
        required: true
        schema:
          type: string
    get:
      tags:
      - CR-Connect
      operationId: pb.get_study_details
      summary: Details about a specific protocol.
      responses:
        200:
          description: Details about the protocol
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudyDetail"
  /check_study/{studyid}:
    parameters:
      - name: studyid
        in: path
        required: true
        description: The id of the study.
        schema:
          type: integer
          format: int32
    get:
      tags:
      - CR-Connect
      operationId: pb.check_study
      summary: IRB Status about a particular study.
      responses:
        200:
          description: Details about the protocol
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudyDetail"
components:
  schemas:
    Study:
      type: object
      properties:
        STUDYID:
          type: number
          example: 11770
          description: The unique id of the study in Protocol Builder.  Sometimes referenced as the "HSR Submission number" if you are looking at Protocol Builder
        HSRNUMBER:
          type: number
          example: 15378
          description: This is the number users use to lookup and reference when talking about non SOM protocols in IRB Online and displayed in more documentation.   Its only used in IRB Online.  Its not an auto increment.
        TITLE:
          type: string
          format: string
          example: The impact of fried pickles on beer consumption in bipedal software developers.
          description: The title of the study, as set in the Protocol Builder.
        NETBADGEID:
          type: string
          format: string
          example: jfg6n
          description: The UVA Id of of the principle investigator for the study.
        Q_COMPLETE:
          type: number
          enum: [0,1]
          example: 0
          description: If 1, then this study is complete in the Protocol Builder, and is ready for processing by CR Connect.
        DATE_MODIFIED:
          type: string
          format: date_time
          example: "2019-12-25T09:12:33.001Z"
          description: The last time this study was modified or updated.
    RequiredDocument:
      type: object
      properties:
        AUXDOCID:
          type: number
          example: 32
          description: The unique and permiment id of the required document.
        AUXDOC:
          type: string
          format: string
          example: IDS - Investigational Drug Service Approval
          description: A descriptive name of the required dcoument.
    Sponsor:
      properties:
        SP_NAME:
          type: string
          example: "AstraZeneca Pharmaceuticals LP (Wilmington, DE)"
          description: A descriptive name
        SP_TYPE:
          type: string
          example: "Industry"
          description: the type of sponsor
        SP_TYPE_GROUP_NAME:
          type: string
          example: "Industry"
          description: The category of the type of sponsor
        SS_STUDY:
          type: number
          example: 15333
          description: The unqiue id of the associated study
        COMMONRULEAGENCY:
          type: boolean
          example: true
          description: Is this a common rule agency
        SPONSOR_ID:
          type: number
          example: 1022
          description: The unique id of the sponsor
    Investigator:
      properties:
        STUDYID:
          type: number
          example: 11770
          description: The unique id of the study in Protocol Builder.
        NETBADGEID:
          type: string
          example: jfg6n
          description: The UVA NetBadge Id of the user.
        INVESTIGATORTYPE:
          type: string
          example: PI
          enum: [PI, SI, DC, SC_I, SC_ii, AS_C, DEPT_CH, IRBC, SCI]
          description: >
            Personnel Type:
             * `PI` - Primary Investigator
             * `SI` - Sub Investigator
             * `DC` - Department Contact
             * `SC_I` - Study Coordinator 1
             * `SC_II` - Study Coordinator 2
             * `AS_C` - Additional Study Coordinators
             * `DEPT_CH` - Department Chair
             * `IRBC` - IRB Coordinator
             * `SCI` - Scientific Contact  (NOT SURE IF THIS IS CORRECT!)
        INVESTIGATORTYPEFULL:
          type: string
          example: Principal Investigator
          description: A human readable descriptive string of the INVESTIGATORTYPE.
    StudyDetail:
      type: object
      properties:
        STUDYID:
          type: number
          example: 11536
          description: The study id from the Protocol Builder
        IS_IND:
          type: number
          enum: [0,1,null]
          example: 0
          description: Does the study involve a new drug?
        IND_1:
          type: string
          description: Investigational New Drug Number, may be several
        IND_2:
          type: string
          description: Investigational New Drug Number, may be several
        IND_3:
          type: string
          description: Investigational New Drug Number, may be several
        IS_UVA_IND:
          type: number
          enum: [0,1,null]
          example: 1
          description: Was the investigational new drug developed at UVa?
        IS_IDE:
          type: number
          enum: [0,1,null]
          example: true
          description: Does the study involve a new device?
        IS_UVA_IDE:
          type: number
          enum: [0,1,null]
          example: 1
          description: Was the investigational device developed at UVa?
        IDE:
          type: string
          description: Investigational Device Number.
        IS_CHART_REVIEW:
          type: number
          enum: [0,1,null]
          example: 1
          description: Does this include chart reviews which do not requre the consent of the Study group?
        IS_RADIATION:
          type: number
          enum: [0,1,null]
          example: true
          description: Does the Study include radiation treatment?
        GCRC_NUMBER:
          type: string
          description: The General Clinical Research Center number, if funded by GCRC
        IS_GCRC:
          type: number
          enum: [0,1,null]
          example: true
          description: Will any part of this study take place in or be funded by the General Clinical Research Center?
        IS_PRC_DSMP:
          type: number
          enum: [0,1,null]
          example: true
          description: Does this protocol involve the testing of a new device or improvement of a method of detection or diagnosis for cancer?
        IS_PRC:
          type: number
          enum: [0,1,null]
          example: true
          description: Does the Study require Cancer Center Protocol Review Committee oversight?
        PRC_NUMBER:
          type: string
          description: Cancer Center Protocol Review Committee number
        IS_IBC:
          type: number
          enum: [0,1,null]
          example: true
          description: Will this Study need the approval of the Institutional Biosafety Committee?
        IBC_NUMBER:
          type: number
          enum: [0,1,null]
          example: true
          description: Site identifier that the location has been approved to handle biological agents by the Institutional Biosafety Committee.
        SPONSORS_PROTOCOL_REVISION_DATE:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the study be part of a UVA faculty member's-sponsored Investigational Device application?
        IS_SPONSOR_MONITORING:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Sponsor monitor the Study?
        IS_AUX:
          type: number
          enum: [0,1,null]
          example: true
          description: Is Auxilliary Info needed?
        IS_SPONSOR:
          type: number
          enum: [0,1,null]
          example: true
          description: Is there an outside sponsor involved?
        IS_GRANT:
          type: number
          enum: [0,1,null]
          example: true
          description: Is grant money funding all or part of the Study?
        IS_COMMITTEE_CONFLICT:
          type: number
          enum: [0,1,null]
          example: true
          description: Does someone on the IRB Review Committee have a conflict of interest?
        DSMB:
          type: number
          enum: [0,1,null]
          example: true
          description: Will this study be monitored by a Data and Safety Monitoring Board?
        DSMB_FREQUENCY:
          type: String
          example: A lot
          description: UNDOCUMENTED.
        IS_DB:
          type: number
          enum: [0,1,null]
          example: true
          description: Is the ONLY intent of this protocol to establish a research database (repository)?
        IS_UVA_DB:
          type: number
          enum: [0,1,null]
          example: true
          description: Will any of the data be kept at UVA outside of the official medical record or will specimens be kept at UVA outside of clinical labs?
        IS_CENTRAL_REG_DB:
          type: number
          enum: [0,1,null]
          example: true
          description: Will any data from UVA subjects be sent to a central registry or database outside of UVA?
        IS_CONSENT_WAIVER:
          type: number
          enum: [0,1,null]
          example: true
          description: Will there be a consent waiver?
        IS_HGT:
          type: number
          enum: [0,1,null]
          example: true
          description: Are you storing specimens, sequences analysis of DNA/RNA for an unspecified future use.
        IS_GENE_TRANSFER:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study involve gene transfer?
        IS_TISSUE_BANKING:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study involve tissue banking?
        IS_SURROGATE_CONSENT:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study require the consent of a surrogate?
        IS_ADULT_PARTICIPANT:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study group include adults?
        IS_MINOR_PARTICIPANT:
          type: number
          enum: [0,1,null]
          example: true
          description: Are any of the subjects between the ages of 15 and < 18?
        IS_MINOR:
          type: number
          enum: [0,1,null]
          example: true
          description: Does the study enroll subjects under the age of 18?
        IS_BIOMEDICAL:
          type: number
          enum: [0,1,null]
          example: true
          description: Will this study involve biomedical research?
        IS_QUALITATIVE:
          type: number
          enum: [0,1,null]
          example: true
          description: Will this study involve only qualitative research?
        IS_PI_SCHOOL:
          type: number
          enum: [0,1,null]
          example: true
          description: Will this study be submitted through the PI's current primary school and department appointment?
        IS_PRISONERS_POP:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study group include prisoners?
        IS_PREGNANT_POP:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study group include pregnant women?
        IS_FETUS_POP:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study be done on fetuses?
        IS_MENTAL_IMPAIRMENT_POP:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study group include anyone who is mentally impaired?
        IS_ELDERLY_POP:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study group include the elderly?
        IS_OTHER_VULNERABLE_POP:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study group include other vulnerable populations?
        OTHER_VULNERABLE_DESC:
          type: string
          example: homeless people
          description: Other vulnerable population description
        IS_MULTI_SITE:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study be conducted at multiple sites?
        IS_UVA_LOCATION:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study be done at UVa?
        NON_UVA_LOCATION:
          type: string
          description: Will the Study be done at non-UVa sites?
        MULTI_SITE_LOCATIONS:
          type: string
          description: List if other sites involved.
        IS_OUTSIDE_CONTRACT:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study be funded by an outside contract?
        IS_UVA_PI_MULTI:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the PI be from UVa for multi-site study?
        IS_NOT_PRC_WAIVER:
          type: number
          enum: [0,1,null]
          example: true
          description: Have you received notification from the Cancer Center Protocol Review Committee (PRC) that this protocol does not need approval from the PRC?
        IS_CANCER_PATIENT:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study involve cancer patients?
        UPLOAD_COMPLETE:
          type: number
          enum: [0,1,null]
          example: true
          description: bit indicating that the study was moved to IRB online
        IS_FUNDING_SOURCE:
          type: number
          enum: [0,1,null]
          example: true
          description: Is there an outside supply source other than the sponsor/funding source supporting this study?
        IS_PI_INITIATED:
          type: number
          enum: [0,1,null]
          example: true
          description: Was the Study initiated by the Principal Investigator?
        IS_ENGAGED_RESEARCH:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study group be contacted by UVa employees or agents or obtain personnally identifiable information about them?
        IS_APPROVED_DEVICE:
          type: number
          enum: [0,1,null]
          example: true
          description: Has the device in the Study been approved by the FDA?
        IS_FINANCIAL_CONFLICT:
          type: number
          enum: [0,1,null]
          example: true
          description: Has the Conflict of Interest Committee provided a COI Management Plan?
        IS_NOT_CONSENT_WAIVER:
          type: number
          enum: [0,1,null]
          example: true
          description: Do you plan on getting VERBAL CONSENT for ONLY a PART of this study (waiver of documentation of consent) and getting WRITTEN CONSENT for another part of the study?
        IS_FOR_CANCER_CENTER:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study involve the UVa Cancer Center?
        IS_REVIEW_BY_CENTRAL_IRB:
          type: number
          enum: [0,1,null]
          example: true
          description: Will the Study require review by the Central IRB?
        IRBREVIEWERADMIN:
          type: string
          example: "dhf8r"
          description: Netbadge id of IRB staff assinged to do the review
